on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      commit_ref:
        type: string
        required: true
jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: tile-generator-repo
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        check-latest: true
        cache: 'pip'
        cache-dependency-path: tile-generator-repo/setup.py

    - id: build-binaries
      run: |
        cd tile-generator-repo
        pip install wheel --plat-name macosx-10-13-x86_64
        python setup.py bdist_wheel --plat-name macosx-10-13-x86_64
        pip install virtualenv --plat-name macosx-10-13-x86_64
        echo "version_string = '${INPUT_VERSION}'" > tile_generator/version.py
        ./pyinstaller/build-binaries.sh
        mv dist dist-"${INPUT_VERSION}"

    - uses: actions/upload-artifact@v3
      with:
        path: tile-generator/dist*
