on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      commit_ref:
        type: string
        required: true
jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: tile_generator
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.7

    - run: |
        echo "version_string = '${INPUT_VERSION}'" > tile_generator/version.py
        ./pyinstaller/build-binaries.sh
        mv dist dist-"${INPUT_VERSION}"

    - uses: actions/upload-artifact@v3
      with:
        path: tile-generator/dist*
